name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program usecases

grade: stable
confinement: strict

apps:
  envtester:
    plugs: [ home ]
    command-chain: [ bin/env-exporter ]
    command: envtester

parts:
  env-exporter:
    source: snap/local
    plugin: dump

  envtester:
    source: .
    plugin: go
    build-snaps: [ go/latest/stable ]

