name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program use cases

grade: stable
confinement: strict

apps:
  myapp1:
    environment:
      env_alias: app1
    extensions:
      - env-injector
    command: env.sh

  myapp2:
    environment:
      env_alias: app2
    extensions:
      - env-injector
    command: env.sh

parts:
  env-exporter:
    source: env.sh
    source-type: file
    plugin: dump


