name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program usecases

grade: stable
confinement: strict

apps:
  myapp1:
    plugs: [ home ]
    environment:
     app_alias: app1
    command-chain: [ bin/env-exporter ]
    command: bin/envtester

  myapp2:
    plugs: [ home ]
    environment:
     app_alias: app2
    command-chain: [ bin/env-exporter ]
    command: bin/envtester

parts:
  env-exporter:
    source: snap/local
    plugin: dump

  envtester:
    source: .
    plugin: go
    build-snaps: [ go/latest/stable ]

