name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program use cases

grade: stable
confinement: strict

apps:
  myapp1:
    daemon: simple
    command-chain:
      - bin/load-myapp1-options.sh
    command: bin/myapp1

  myapp2:
    daemon: simple
    command-chain:
      - bin/load-myapp2-options.sh
    command: bin/myapp2

parts:
  local:
    source: snap/local
    plugin: dump

  envtester:
    source: .
    plugin: go
    build-snaps:
      - go/latest/stable

  myapp2:
    source: myapp2
    plugin: dump
    organize:
      run.sh: bin/myapp2