name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program use cases

grade: stable
confinement: strict

apps:
  myapp1:
    daemon: simple
    environment:
     env_alias: myapp1
    extensions:
      - env-injector
    command: bin/envtester

  myapp2:
    daemon: simple
    environment:
     env_alias: myapp2
    extensions:
      - env-injector
    command: bin/envtester

  # an app to print all the envs for myapp1
  myapp1-env:
    environment:
     env_alias: myapp1
    extensions:
      - env-injector
    command: bin/env.sh

parts:
  env-exporter:
    source: snap/local
    plugin: dump

  envtester:
    source: .
    plugin: go
    build-snaps: [ go/latest/stable ]

