name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program usecases

grade: stable
confinement: strict

apps:
  myapp1:
    plugs: [ home ]
    command: bin/envtester

  myapp2:
    plugs: [ home ]
    command: bin/envtester

parts:
  envtester:
    source: .
    plugin: go
    build-snaps: [ go/latest/stable ]

