name: envtester
base: core24
version: 'demo'
summary: Demonstration of env-exporter program
description: |
  envtester is a demo snap to show the env-exporter program usecases

grade: stable
confinement: strict

hooks:
  configure:
    environment:
      env_apps: "myapp1,myapp2"

apps:
  myapp1:
    plugs: [ home ]
    environment:
     env_alias: myapp1
     env_debug: "true"
    command-chain:
      - bin/env-exporter
    command: bin/envtester

  myapp2:
    plugs: [ home ]
    environment:
     env_alias: myapp2
    command-chain:
      - bin/env-exporter
    command: bin/envtester

  # an app that doesn't use the exporter
  myapp-no-env:
    command: bin/envtester

  # an app to print all the envs for myapp1
  myapp1-env:
    plugs: [ home ]
    environment:
     env_alias: myapp1
     env_debug: "true"
    command-chain: 
      - bin/env-exporter
    command: bin/env.sh

parts:
  env-exporter:
    source: snap/local
    plugin: dump
  
  binary-env-exporter:
    after:
      - env-exporter
    source: exporter
    plugin: nil
    build-snaps:
      - rustup
    build-packages:
      - musl-tools
    override-build: |

      rustup default stable
      rustup target add x86_64-unknown-linux-musl

      cargo build --target x86_64-unknown-linux-musl --release
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp target/x86_64-unknown-linux-musl/release/env-exporter $SNAPCRAFT_PART_INSTALL/bin/
      


  curl-client:
    plugin: nil
    stage-packages:
      - curl

  envtester:
    source: .
    plugin: go
    build-snaps: [ go/latest/stable ]

